-- Live cross-tenant coverage is run by `npm run test:tenant`.
-- It signs in separately as Alpha and Beta and asserts that reads, writes, deletes,
-- storage enumeration, and cross-tenant payment references are all blocked by RLS.
-- Configure SUPABASE_TEST_* variables listed in .env.example before running it.
