"use client";

import { useState } from "react";

type Client = { id: string; name: string };
type Item = { description: string; quantity: number; unitPrice: number; discountAmount: number; taxRate: number };
const blankItem: Item = { description: "", quantity: 1, unitPrice: 0, discountAmount: 0, taxRate: 15 };

export function FinancialDocumentForm({ businessId, clients, action, submitLabel, dateLabel, recurring = false }: { businessId: string; clients: Client[]; action: (formData: FormData) => void; submitLabel: string; dateLabel: string; recurring?: boolean }) {
  const [items, setItems] = useState<Item[]>([{ ...blankItem }]);
  const update = (index: number, field: keyof Item, value: string) => setItems((previous) => previous.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: field === "description" ? value : Number(value) } : item));
  const total = items.reduce((sum, item) => sum + Math.max(0, item.quantity * item.unitPrice - item.discountAmount) * (1 + item.taxRate / 100), 0);
  return <form action={action} className="document-form"><input type="hidden" name="businessId" value={businessId} /><input type="hidden" name="itemsJson" value={JSON.stringify(items)} /><label>Client<select name="clientId" required defaultValue=""><option value="" disabled>Select a client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label><label>{dateLabel}<input name="dueDate" type="date" /></label>{recurring && <div className="form-grid"><label>Frequency<select name="frequency" defaultValue="monthly"><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label><label>Payment due after (days)<input name="dueDays" type="number" min="0" max="365" defaultValue="14" required /></label></div>}<div className="item-list"><div className="item-head"><span>Description</span><span>Qty</span><span>Unit price</span><span>Discount</span><span>VAT %</span></div>{items.map((item, index) => <div className="item-row" key={index}><input aria-label="Description" value={item.description} onChange={(event) => update(index, "description", event.target.value)} required /><input aria-label="Quantity" type="number" min="0.0001" step="0.0001" value={item.quantity} onChange={(event) => update(index, "quantity", event.target.value)} required /><input aria-label="Unit price" type="number" min="0" step="0.01" value={item.unitPrice} onChange={(event) => update(index, "unitPrice", event.target.value)} required /><input aria-label="Discount amount" type="number" min="0" step="0.01" value={item.discountAmount} onChange={(event) => update(index, "discountAmount", event.target.value)} required /><input aria-label="VAT rate" type="number" min="0" max="100" step="0.01" value={item.taxRate} onChange={(event) => update(index, "taxRate", event.target.value)} required /><button type="button" onClick={() => setItems((previous) => previous.filter((_, itemIndex) => itemIndex !== index))} disabled={items.length === 1}>Remove</button></div>)}</div><button type="button" className="text-button" onClick={() => setItems((previous) => [...previous, { ...blankItem }])}>+ Add line</button><label>Notes<textarea name="notes" rows={4} maxLength={4000} /></label><p className="estimate">Estimated total <strong>R {total.toFixed(2)}</strong></p><button className="button" type="submit" disabled={clients.length === 0}>{submitLabel}</button>{clients.length === 0 && <p role="alert">Create a client before creating a document.</p>}</form>;
}
